### ISSUE TITLE
Address book

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#12]
While testing a bunch copying and pasting was getting very old. Having a address book next to or around the qr scanner on address line in the send menu would be helpful when sending to the same address and just in general. 
![IMG_0920](https://github.com/steel97/veil_wallet/assets/46406370/d691129d-b3b5-4b80-9438-fad2b72e7edb)

**Comment by steel97** [comment]
Good suggestion! Will add it to my TO-DO list

**Comment by steel97** [comment]
Done! Please note, address book and address history is stored in non-encrypted storage

**Comment by ohcee** [comment]
@steel97 Works great, have tested on Linux and iPhone. 

One thing to maybe add for ease is when you add the a new address to able use a qt scanner to enter the address. Having a qt button on the `Address` line. Just like the `Recipient address` line in the send menu.
