### ISSUE TITLE
Sending transaction not created 

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#3]
**Issue**
When trying to send VEIL to another wallet I get an error saying it cannot create the transaction. I have tried with the subtract fee added and not added. I have tried with VPN on/off and WiFi on/off. Same result from each different case. 

**Expected behavior**
A transaction should be created and sent to the address.

**Screenshots**
![IMG_0839](https://github.com/steel97/veil_wallet/assets/46406370/9fc54155-a957-43b4-a820-172a068ae54c)
![IMG_0838](https://github.com/steel97/veil_wallet/assets/46406370/3d62aab7-0c71-40d6-b3ec-a143099808eb)

**Smartphone**
 - Device: iPhone 11
 - OS: iOS
 - Version 17.1.1

**Comment by steel97** [comment]
> **Issue** When trying to send VEIL to another wallet I get an error saying it cannot create the transaction. I have tried with the subtract fee added and not added. I have tried with VPN on/off and WiFi on/off. Same result from each different case.
> 
> **Expected behavior** A transaction should be created and sent to the address.
> 
> **Screenshots** ![IMG_0839](https://user-images.githubusercontent.com/46406370/283827438-9fc54155-a957-43b4-a820-172a068ae54c.png) ![IMG_0838](https://user-images.githubusercontent.com/46406370/283827523-3d62aab7-0c71-40d6-b3ec-a143099808eb.png)
> 
> **Smartphone**
> 
> * Device: iPhone 11
> * OS: iOS
> * Version 17.1.1

Is this issue exists with latest automated build? I made some changes to fix this today
