### ISSUE TITLE
Added a VEIL balance near the USD amount

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#5]
Most users including myself would like to know the VEIL balance not just the price in USD. 
I suggest adding the wallet users VEIL balance near or by the USD amount icon. 

Anywhere around the circle would be perfect.

![IMG_0843](https://github.com/steel97/veil_wallet/assets/46406370/5b9a93e9-da6c-42c0-b4fa-41bd56d6ddab)

**Comment by steel97** [comment]
It should be already there:
![IMG_1859](https://github.com/steel97/veil_wallet/assets/7414151/fb90186f-e812-4068-a7d9-997d8008ccfc)
But I see you probably have some custom font settings? It might affect display behaviour, I’ll check it a little bit later

**Comment by ohcee** [comment]
This also seems to have been fixed with the latest. Closing this issue.

**Comment by steel97** [comment]
Will check it out, thanks for information!

**Comment by ohcee** [comment]
Update after adding a bigger amount the veil balance shows. Also that caused the the address to leave the box with the balances. ![image](https://github.com/steel97/veil_wallet/assets/46406370/965dd94d-d16a-45c1-a03e-d55b11556002)

iPhone 11
iOS 17.1.1

**Comment by steel97** [comment]
@ohcee could you please check latest build from actions tab? I made auto-scaling of font to match available width, also made logo a little bit smaller

**Comment by ohcee** [comment]
I will try when I get back to desktop.

**Comment by ohcee** [comment]
The new update has fixed this problem. Good job!
