### ISSUE TITLE
Multiple default wallet selections

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#8]
**Describe the bug**
Multiple default wallet selections. 

**Expected behavior**
One default wallet

**Screenshots**
![multi default wallets happen on first launch](https://github.com/steel97/veil_wallet/assets/46406370/f157e5d3-ddf5-44a9-ad86-9edff6c0ecdb)

**Desktop:**
 - OS: Ubuntu 22.04.3

**Comment by steel97** [comment]
I think this bug appears because of tests from https://github.com/steel97/veil_wallet/issues/7
wallets was created, but due to bug can't be selected, you can freely delete them

**Comment by steel97** [comment]
I think issue fixed now. I would appreciate if you can help testing this on new virtual machine (unfortunately I have issues with virtualization now due to settings on my windows machine, so I can't use GUI version of ubuntu on virtualbox right now)

**Comment by ohcee** [comment]
I think its fixed. I don't have 4 random default I have the 3 different wallets I made or imported. I only had one yesterday before I started making new addresses for max balance testing. 

Side note: I deleted the wallet data and wallet and re-downloaded the new wallet and re-installed. I was expecting the wallet to want a new import or to create a new wallet but instead it had my three defaults from prior. I not sure why that is or if I missed something somewhere.

**Comment by steel97** [comment]
> Side note: I deleted the wallet data and wallet and re-downloaded the new wallet and re-installed. I was expecting the wallet to want a new import or to create a new wallet but instead it had my three defaults from prior. I not sure why that is or if I missed something somewhere.

This depends on OS and how you deleted wallet. Data stored in encrypted storage, (which is different on all platforms), for example, on windows it's enough to delete `%APPDATA%/org.veilproject/` folder, on android - just delete application and all related data will be erased.

**Comment by steel97** [comment]
Closing the issue for now. We can re-open it later if this happens again.
