### ISSUE TITLE
Scan QR code button not working

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#9]
**Describe the bug**
When trying to open/press the QR code (left corner) button nothing happens.

**Expected behavior**
QR code to address appears on screen.

**Screenshots**
![scan qr button doesn't work](https://github.com/steel97/veil_wallet/assets/46406370/1e3a4063-1bc3-495e-b30b-1d60829dc5ea)

**Desktop:**
 - OS: Ubuntu 22.04.3

**Comment by steel97** [comment]
QR code scanning is unsupported on desktop platforms (it's grayed out to show that).
I can remove it, but UI would not look as good as with that button (even if it's grayed out)

**Comment by ohcee** [comment]
Understood. Personally I would remove it if it does not work, due to it might confuse users into thinking that it should be working and its not (like it did me lol).

**Comment by steel97** [comment]
Looks reasonable, will leave issue open, while thinking.
Thanks!

**Comment by steel97** [comment]
Done, now tooltip shows that QR scanning is unavailable
